{% set name = "marp-cli" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marp-team/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 21d33ca85cf35baa63620cb56c177c58d285f6e38a1be3c020dca681c5684dd1

build:
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - marp --help

about:
  home: https://github.com/marp-team/marp-cli
  summary: 'A CLI interface for Marp and Marpit based converters'
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - kklein
