{% set name = "marp-cli" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marp-team/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ce87fdb74b73a3aad06b53d233c38e9f2c11b284f7d0adf588e92ebc3caece31

build:
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - marp --help

about:
  home: https://github.com/marp-team/marp-cli
  summary: 'A CLI interface for Marp and Marpit based converters'
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - kklein
