{% set name = "marp-cli" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marp-team/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d75e2794077611ba0d7808a2a2392bb694730a82999a5108eb822e2b1202db6

build:
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - marp --help

about:
  home: https://github.com/marp-team/marp-cli
  summary: 'A CLI interface for Marp and Marpit based converters'
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - kklein
