{% set name = "marp-cli" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marp-team/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 37f874f8e6a604cc1236124c2ffaeed2edc17b8e42ff25c3148c2ac11febe79f

build:
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - marp --help

about:
  home: https://github.com/marp-team/marp-cli
  summary: 'A CLI interface for Marp and Marpit based converters'
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - kklein
