{% set name = "marp-cli" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marp-team/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 171e2c0654a5a485e0444a46a7e483043f97bee5cb09f8e6de59c49f0ea3729e

build:
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
  host:
    - nodejs
    - pnpm
    - pnpm-licenses >=2.1.0
  run:
    - nodejs

test:
  commands:
    - marp --help

about:
  home: https://github.com/marp-team/marp-cli
  summary: 'A CLI interface for Marp and Marpit based converters'
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - kklein
